name:                timeline
version:             0.1.0.0
github:              "Cj-bc/timeline"
license:             BSD3
author:              "Cj.bc_sd a.k.a Cj-bc"
maintainer:          "cj.bc-sd@outlook.jp"
copyright:           "MIT"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Cj-bc/timeline#readme>

dependencies:
- base >= 4.7 && < 5
- iCalendar
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- vector
- text

library:
  source-dirs: src

executables:
  timeline-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeline

tests:
  timeline-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeline
